### ISSUE TITLE
Twitter Notifications 403 error

### ISSUE THREAD

**Issue by billyhoush** [kalouo/breadcrumbs#76]
Hello,

Using  0.0.10-alpha.2

Starting on cycle 620 Twitter notifications were producing this error:

`Sending notifications via Twitter
ApiResponseError: Request failed with code 403
    at RequestHandlerHelper.createResponseError (C:\snapshot\breadcrumbs\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:103:16)
    at RequestHandlerHelper.onResponseEndHandler (C:\snapshot\breadcrumbs\node_modules\twitter-api-v2\dist\client-mixins\request-handler.helper.js:252:25)
    at Gunzip.emit (node:events:527:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  error: true,
  type: 'response',
  code: 403,
  headers: {
    date: 'Wed, 21 Jun 2023 03:18:36 UTC',
    perf: '7626143928',
    server: 'tsa_b',
    'set-cookie': [
      'guest_id_marketing=v1%3A168731751680348393; Max-Age=63072000; Expires=Fri, 20 Jun 2025 03:18:36 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id_ads=v1%3A168731751680348393; Max-Age=63072000; Expires=Fri, 20 Jun 2025 03:18:36 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'personalization_id="v1_QITNUczc/tSMAmplLXcWpg=="; Max-Age=63072000; Expires=Fri, 20 Jun 2025 03:18:36 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
      'guest_id=v1%3A168731751680348393; Max-Age=63072000; Expires=Fri, 20 Jun 2025 03:18:36 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None'
    ],
    'api-version': '2.65',
    'content-type': 'application/json; charset=utf-8',
    'cache-control': 'no-cache, no-store, max-age=0',
    'content-length': '328',
    'x-access-level': 'read-write',
    'x-frame-options': 'SAMEORIGIN',
    'content-encoding': 'gzip',
    'x-transaction-id': '2266898de62cd8b8',
    'x-xss-protection': '0',
    'x-rate-limit-limit': '40000',
    'x-rate-limit-reset': '1687318416',
    'content-disposition': 'attachment; filename=json.json',
    'x-content-type-options': 'nosniff',
    'x-rate-limit-remaining': '39999',
    'strict-transport-security': 'max-age=631138519',
    'x-response-time': '18',
    'x-connection-hash': '9a97b463303e407134aa710a570e86963ea7fb565414b8bbd11ab062c94bdefc',
    connection: 'close'
  },
  rateLimit: { limit: 40000, remaining: 39999, reset: 1687318416 },
  data: {
    client_id: '22840067',
    detail: 'When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.',
    registration_url: 'https://developer.twitter.com/en/docs/projects/overview',
    title: 'Client Forbidden',
    required_enrollment: 'Appropriate Level of API Access',
    reason: 'client-not-enrolled',
    type: 'https://api.twitter.com/2/problems/client-forbidden'
  }
}
Twitter notifications sent`

I have tried using new api and access keys/tokens to no avail. Any assistance would be much appreciated.

**Comment by billyhoush** [comment]
Issue fixed and was due to API changes since Twitter Developer portal changed. You can't run the APP as standalone and you have to add it to a project. I have included a screenshot of the correct configuration. After I added it to the project, it worked as usual.
![8jq8uHDc](https://github.com/tezos-breadcrumbs/breadcrumbs/assets/95115794/a99eec75-fabc-47e5-9a7d-2ab6dccc227a)
